<?php

class MLSOpenHouseView extends AbstractMLSIndexView {
    
    public function __construct($models, AbstractUITableView $uiTableView, AbstractMLSListing $sampleModel, GI_SearchView $searchView = NULL) {
        parent::__construct($models, $uiTableView, $sampleModel, $searchView);
        $this->addCSS('resources/css/search.css');
        $this->addCSS('resources/css/open_house.css');
        
        //Add metatag
        $this->addSiteTitle('Open house Listings');
        $this->setDescription('Search Open house Listings');
    }
    
    public function setSearchForm(GI_Form $form){
        $this->form = $form;
        $this->buildSearchForm($this->searchArray);
    }
    
    public function setMLSListings($mlsListings){
        $this->mlsListings = $mlsListings;
    }
    
    public function setPageBar($pageBar){
        $this->pageBar = $pageBar;
    }
    
    public function setSearchArray($searchArray){
        $this->searchArray = $searchArray;
    }
    
    public function setQueryId($queryId){
        $this->queryId = $queryId;
        return $this;
    }
    
    public function beforeReturningView() {
        $this->buildView();
    }
    
    public function buildView(){
        $this->addHeaderBannerSection();
        $this->addMainContentSection();
    }
    
    protected function addHeaderBannerSection() {
        $this->addHTML('<section class="header-banner-section openhouse-banner-section">');
            $this->addHTML('<div class="header-banner">');
                $this->addHTML('<div class="container">');
                    $this->addHTML('<div class="banner-caption">');
                        $this->addHTML('<h1 class="title">Open House</h1>');
                    $this->addHTML('</div><!--.banner-caption-->');
                $this->addHTML('</div><!--.container-->');
            $this->addHTML('</div><!--.header-banner-->');
        $this->addHTML('</section>');
    }
    
    protected function addMainContentSection() {
        $this->addHTML('<section class="main-content-section mls-openhouse-section list-section">');
            $this->addHTML('<div class="container">');
                //$this->buildBtns();
                $this->buildTitle();
                $this->buildTable();
            $this->addHTML('</div><!--.container-->');
        $this->addHTML('</section>');
    }
    
    protected function buildTitle() {
        $this->addHTML('<h2 class="section-title">Open houses</h2>');
    }
    
    protected function buildTable() {
        if (count($this->mlsListings) > 0) {
            $pageBarHTML = $this->pageBar->getHTMLView();
            if($this->addWrap && $this->pageBar){
                $this->addHTML($pageBarHTML);
            }
            $this->addHTML('<div class="ui_table_wrap row ui_list_row" id="list_table">');
            foreach($this->mlsListings as $mlsListing){
                $this->addHTML('<div class="ui_table_col col-lg-12 type_'.$mlsListing->getTypeRef().'">');
                $itemView = new MLSOpenHouseItemView($mlsListing, $this->queryId);
                $this->addHTML($itemView->getHTMLView());
                $this->addHTML('</div>');
            }
            $this->addHTML('</div>');

            if($this->addWrap && $this->pageBar){
                $this->addHTML($pageBarHTML);
            }

            if ($this->addWrap) {
                $this->addMLSStatement();
            }
        } else {
            $this->addHTML('<div class="no_data">No open houses found.</div>');
        }
    }
    
    
    public function getHTMLView($buildView = true){
        if($buildView){
            $this->buildView();
        }
        else{
            $this->addContent($this->form->getForm());
        }
        return $this->html;
    }
    protected function addMLSStatement() {
        $this->addHTML('<div class="mls_statement justified">
                            <img src="resources/css/images/mls_logo_large.png" alt="MLS logo">
                            <p>This representation is based in whole or in part on data generated by the Chilliwack & District Real Estate Board, Fraser Valley Real Estate Board or Real Estate Board of Greater Vancouver which assumes no responsibility for its accuracy</p>
                        </div>');
    }
}
